version: '3.9'
services:
  postgres:
    privileged: true
    image: docker.io/library/postgres:14
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

  ## Hasura is compatible with CockroachDB 22.2 onwards
  cockroach:
    privileged: true
    image: docker.io/cockroachdb/cockroach:v22.2.1
    # starts an _insecure_, single-node CockroachDB intended for non-production uses only
    # follow the CockroachDB Cloud Guide to connect to a production CockroachDB cluster
    command:
      - start-single-node
      - --insecure
      - --accept-sql-without-tls
    ports:
      - '26257:26257'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v2/databases/torad/" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    environment:
      COCKROACH_USER: 'root'
      COCKROACH_DATABASE: 'torad'
    volumes:
      - '${PWD}/volumes/cockroach:/cockroach/cockroach-data'

  graphql-engine:
    privileged: true
    image: docker.io/hasura/graphql-engine:v2.20.0.cli-migrations-v3
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      cockroach:
        condition: service_healthy
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## cockroachdb
      HASURA_GRAPHQL_DB_COCKROACH: postgres://root@cockroach:26257/torad?sslmode=disable
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
      - '${PWD}/hasura/migrations:/hasura-migrations:ro'
      - '${PWD}/hasura/metadata:/hasura-metadata:ro'
volumes:
  cockroach-data:
